version: "3"

tasks:
  swaggo:
    cmd: swag init

  migcr:
    cmd: migrate create -ext sql -dir ./migrations -seq {{.name}}

  test:
    cmd: go test ./...

  run:
    cmd: go run main.go serve --port 8080

  fmt:
    cmd: go fmt && swag fmt

  build:
    cmd: swag init && go build -o main .
