version: "3"

tasks:
  migcr:
    cmd: migrate create -ext sql -dir ./migrations -seq {{.name}}

  init:
    cmds:
      - swag init
      - echo .env_sample > .env

  run:
    cmds:
      - bash platform/script/run-lgtm.sh
      - go run main.go serve --port 8080

  fmt:
    cmd: go fmt && swag fmt

  test:
    cmd: go test ./...

  build:
    cmd: swag init && go build -o main .
